### ISSUE TITLE
ios 13.3.1 on free developer account

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#1264]
**Describe the bug**
Loop install failing on iOS 13.3.1 both dev and master branches

**Attach an Issue Report**

I know others are seeing a amplitude build failure, but on my attempts to start debugging this issue...I'm getting the failure to install message below. The build itself succeeds. I built on two different free developer accounts, both of which had not built any apps in months so they should not have exceeded any maximum number of apps...unless somehow loop's build process is suddenly counting as multiple apps in one??

<img width="1011" alt="Screen Shot 2020-02-07 at 10 18 59 AM" src="https://user-images.githubusercontent.com/12402160/74055279-8eeb6380-4994-11ea-918a-593c8b5dc0ac.png">

**To Reproduce**
Build on iOS 13.3.1 with free account

**Phone**
 - Hardware: iPhone XSmax
 - OS Version: 13.3.1

**Loop Version**
 - Version Number: v2.0 master
 - Repo: LoopKit/Loop

**Comment by ps2** [comment]
Where there other "free" built apps on the phone? Wondering if this is a limit to number of installed apps on the phone.

**Comment by Kdisimone** [comment]
Nope. No other free-built apps on the phone

**Comment by tkk41** [comment]
One of my last tries (free dev and 13.3.1), I can remember to this "limit" stuff, was totally wondering about this error

**Comment by biesbjerg** [comment]
@Kdisimone could you try checking if you may have multiple apps listed as [described here](https://apple.stackexchange.com/a/334929)?

**Comment by Kdisimone** [comment]
As stated above, no other apps are installed on device. 

I checked the Xcode lists, but also I know that the only two apps that I ever install are Loop and resetTransmitter. And those are with paid account. And both deleted for purposes of debugging this issue.

**Comment by Kdisimone** [comment]
Thanks for nada Apple. They suggested "behaves as expected. Delete other apps installed on phone". Argh. Don't have other apps on phone.

**Comment by Kdisimone** [comment]
@ps2 im not sure of the conversion between cocoa pods and carthage but....similar must exist?

https://github.com/Alamofire/Alamofire/issues/3051

**Comment by Kdisimone** [comment]
"Are you using a non-developer Apple ID to install the app to your phone? It looks like iOS 13.3.1 has broken apps installed with free Apple IDs, but only if they contain embedded frameworks. If it's possible to link all your dependencies as static libraries rather than frameworks (for example, if you're using Cocoapods you can remove use_frameworks! from your Podfile), that should fix the issue for now."

I do have a feedback open with apple's Feedback Assistant but no traction on this thus far.

**Comment by kulczwoj** [comment]
I guess this issue is connected with my problems on Apple Watch after upgrading it to 6.1.1 (see thread https://github.com/LoopKit/Loop/issues/1211) I'm also using a non-developer Apple ID.

**Comment by cyoung1024** [comment]
I'm still getting this on iOS 13.4, personally. MacOS 10.15.4, Xcode 11.4, iPhone X, computer restarted multiple times, observed when attempting with master, dev, and dev-spike. Tried downloading zip's of master and dev instead of just from my local git branches as well. I know others had success with free dev accounts and 13.4, but it's not the case for me. Happy to give more details if there's anything I missed. Screenshots are from my 5th attempt building, with dev.
<img width="1280" alt="Unable to install" src="https://user-images.githubusercontent.com/42605906/77859665-10c87200-720b-11ea-9c16-c5d7a2bd34ff.png">
<img width="1280" alt="Error" src="https://user-images.githubusercontent.com/42605906/77859670-14f48f80-720b-11ea-8201-996d3bb9e724.png">
<img width="800" alt="Device" src="https://user-images.githubusercontent.com/42605906/77859673-19b94380-720b-11ea-9b44-03312f613d00.png">
