### ISSUE TITLE
Apple Watch Gray overrides/Pre-Meal

### ISSUE THREAD

**Issue by Trpl7ca** [LoopKit/Loop#1761]
Randomly the override Preset on the watch will gray out. This happens even though there has been no  override selected. You can correct the problem by selecting an override on the phone. Some have reported this also happens with Pre-Meal.

[Loop Report 2022-08-01 08:30:32-07:00.md](https://github.com/LoopKit/Loop/files/9235153/Loop.Report.2022-08-01.08.30.32-07.00.md)

**To Reproduce**
It is random, just grays out.

**Expected behavior**
Preset and Pre-Meal remain selectable on watch

**Phone**
Iphone 13 pro
 - OS Version: 15.6

**Loop Version**
workspaceGitRevision: 1d88ec0
![incoming-F10C0776-A4B0-4B28-9A51-58032AFC415F](https://user-images.githubusercontent.com/52380252/182186060-1a758689-68fa-4bc8-a4e0-f453d3642944.PNG)

**CGM**
G6

**Pump**
Omnipod Dash

**Additional context**
![incoming-F10C0776-A4B0-4B28-9A51-58032AFC415F](https://user-images.githubusercontent.com/52380252/182186575-418fe663-d0f1-4f9b-8e1f-4a67c21c1dd9.PNG)

**Comment by Trpl7ca** [comment]
![incoming-D4D00869-B8AD-4A68-8A5E-72C4222939D1](https://user-images.githubusercontent.com/52380252/182187514-8581af83-26a6-46e4-b56f-166ccc539df9.PNG)

**Comment by marionbarker** [comment]
Just happened to me. Maybe 3rd time I’ve seen this. Selecting override on phone sufficient to clear the problem. 
workspaceGitRevision: 9c48e05

**Comment by Trpl7ca** [comment]
It happens to me every couple of days but yet to understand why.

**Comment by marionbarker** [comment]
I assume this is related. Had the same symptom following new sensor start and in addition to the greyed out override, the red loop icon on watch did not update after sensor warmed up and loop was green on phone.  

This time tried touching override on phone-no effect. 
Restarted Loop app on phone-no effect. 
Restarted watch and problem resolved.

**Comment by BobbyG1961** [comment]
I just experienced this too. Had grey overrides on the watch after changing sensor. Touched random override on the phone, and watch override option lit up. [Loop Report 2022-08-05 16:59:21-04:00.md](https://github.com/LoopKit/Loop/files/9271668/Loop.Report.2022-08-05.16.59.21-04.00.md)

**Comment by Trpl7ca** [comment]
I have had at least one grayed out event for the last couple of days. There was no sensor change involved so at least for me no connection. Also I left it alone, as in I did not cycle override on phone and it self corrected some time later.

**Comment by ps2** [comment]
I looked through the code involved in enabling and disabling these buttons, and haven't come up with any theories as to what could be causing this. The pre-meal should only be disabled if you do not have a pre-meal target range configured, and the override button should only be disabled when there are no overrides configured.  It's likely that this is related to all the recent re-work of settings storage, but without a way to reliably reproduce, I'm not able to provide a fix.

If anyone notices this happening again, please note the time you noticed it, and if you remember when you last saw it active. Then, please export critical device logs from Loop and DM them to me in zulip, or post them. I want to review the stored settings history and see if there are settings being stored at times without pre-meal ranges or overrides.

**Comment by shainey** [comment]
Hi Pete,
I am also encountering this situation over the last few Commits.  I believe it has been since insulin the 7/31 Commit.  

If I open the Loop cell app to turn on the Custom Preset or Pre-Meal Preset, the watch buttons are active again & functional.  

After taking off the watch to charge it and then putting it back on, the buttons are greyed out again. 

Hope this helps you with this, Steve

![Loop Watch Issue](https://user-images.githubusercontent.com/22161266/184548428-5e930fe8-52d4-411e-9c7e-8c526d4bd71d.jpg)
[Loop Report 2022-08-14 133520-0400.md](https://github.com/LoopKit/Loop/files/9333824/Loop.Report.2022-08-14.133520-0400.md)


**Phone**
 - Hardware: iPhone 11 Pro Max
 - OS Version: iOS 15.6

**Loop Version**
 - Version Number: Dev Aug 4 Commit 6ae754e

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet Pod & Dash (Using both)
 - Model: Dash
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Comment by rteague-dr** [comment]
For me it seems to happen when I place my watch on the charger. When I take it off the charger the buttons are disabled. This is pretty consistent since I updated on Aug 7th.

**Comment by ps2** [comment]
I just pushed updates to add additional logging.  If you would like to help with this issue, please install the latest dev, verify that the icons are enabled (do whatever you need to to get them enabled), then wait until you see the issue appear again.  At that point, please note the time, and capture a sysdiagnose, and send me the link to the sysdiagnose (DM me on zulip, or post on zulip or here) along with the time.

**Comment by shainey** [comment]
Heading out now, but will do it later this evening.

**Comment by skimaniac** [comment]
same problem here, but I think if I leave loop on the watch open long enough everything goes back to normal.

Yesterday grey icon, and today it's ok. 

i will send critical device log to you @ps2 on zulip

**Comment by shainey** [comment]
I installed the last Dev Commit 8/14 and still have the same issue I reported on my Dev Aug 4 Commit Crashing My Watch App #1769 issue.  I can install it on the watch directly to my watch from Xcode through the phone by following these instructions, but I did not need to complete this process before the Dev Commit 7/31: https://loopkit.github.io/loopdocs/build/build_errors/#apple-watch-loop-app-not-running-on-watch 

After doing this, it works on the watch with the Pre-Meal Preset & Custom Preset working after the buttons are greyed out for a second & then come alive.

I also determined that when the Therapy Settings > Pre-Meal Ranges are not entered, it does Grey Out the  Pre-Meal.  That being said, maybe installing it without the Pre-Meal Range values is causing both the buttons to be impacted, as I didn't have them enter before this evening's update.

Do others having this issue have their Pre-Meal Ranges entered or not to validate this assumption?

**Comment by shainey** [comment]
Okay, my assumption above was incorrect being I entered the Pre-meal Range values last evening and it happened again today.  

Here are the Issue & Critical Event Log reports. I noticed the greyed out buttons, applied the Temp Override on the cell which brought the buttons back and then ran the reports a few mins later.   

[Export-20220815T120121Z.zip](https://github.com/LoopKit/Loop/files/9337231/Export-20220815T120121Z.zip)

**Comment by ps2** [comment]
Thanks for the reports. I think people have missed that to see the recently added logs, I'll need a *sysdiagnose*. That's a little more work to share, as it's large, and takes a little time. You'll need to share it from a file sharing service. 

https://it-training.apple.com/tutorials/support/sup_using-sysdiagnose-ios-ipados

**Comment by shainey** [comment]
Can someone else who’s also seeing this issue help Pete out on give him the sysdiagnose report referenced above?

I’m am traveling for business, don’t have my MacBook & will not be able to complete this until this weekend.  Thx! Steve
