### ISSUE TITLE
Loop screen with a very high (deadly) blood glucose not in line with the actual blood glucose 

### ISSUE THREAD

**Issue by FransLuijendijk** [LoopKit/Loop#912]
![IMG_1441](https://user-images.githubusercontent.com/49094555/55275527-b8a11c00-52e7-11e9-8cf2-c78d786837e7.png)

iPhone 8
Loopkit v1.9.5

Since this morning Loop shows a value of 50.7 mom/l as the actual blood glucose value although the reading in the graph shows the real value that is also the value shown in the Dexcom App (4.1 mol/l). It also gives a predicted value of 50.7 mol/l. The graph is going up to 195 mom/l en tapping the graph I'm redirected to the settings for the predictive algorithm, but as soon as that page shows up in the app it is not responsive and after several seconds the App crashes. Due to the fact that the predictive algorithm is not working correctly it is also not possible to get an advise for a bolus based upon the bolus calculation.

I removed the app completely and removed all settings from my iPhone. Then I made a new build with the latest version of LoopKit. After building the App and installation on my iPhone it shows exactly the same screen again and the App and predictive algorithm doesn't work correctly.

Please advise.

Frans

**Comment by Kdisimone** [comment]
Are you 100% certain you are on Loop v1.9.5?  The one released just days ago?

The reason I ask is that your issue is here https://github.com/LoopKit/Loop/issues/834

And there has been a fix released for that. So either the fix has a problem or your mistaken about which version of Loop you’re using. 

And, don’t worry, Loop will not loop on that future data point.

**Comment by FransLuijendijk** [comment]
Hi Katie,

Thanks for the quick reply. Missed that issue. As for your information. Yes I downloaded this morning the newest version as you can see in the enclosed screenshot. So it seems the fix still has the problem.

Based upon your information I deleted the future values in Apple Health and things are back to normal.

Best regards and thanks for the help.

Frans

**Comment by ps2** [comment]
@FransLuijendijk The fix doesn't go back and re-decode values that were incorrectly decoded, so just by upgrading, you would expect the value to stay there (and you would need to delete it via HK). If you see a *new* future bg value show up on a new version of Loop, that would indicate the problem still exists, but so far it doesn't sound like that has happened.

**Comment by FransLuijendijk** [comment]
Makes sense since I did not delete the data stored in Apple Health.

Thanks for all the help.

Frans

**Comment by FransLuijendijk** [comment]
BTW. Don’t know where to leave ideas behind on future  development of Loop, but I would love to see a CarPlay version. That would make things very convenient.

Best to all of you,

Frans
